language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit

warnings_are_errors: false

services:
    - mysql

php:
    - 7.2

install:
    - composer update --prefer-dist --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test

script:
    - echo "coucou"
