name: CI Travis Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: My first action
      uses = travis-ci/actions@master
      env:
        TRAVIS_TOKEN: ${{ secrets.SECRET_TRAVIS_CI }}
